modLoader = "javafml"
loaderVersion = "[40,)"
license = "CC BY-NC-ND 4.0"
issueTrackerURL = "https://github.com/Faboslav/friends-and-foes-beekeeper-hut-beekeeper-hut/issues"

[[mods]]
modId = "beekeeperhut"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.jpg"

[[dependencies.beekeeperhut]]
modId = "forge"
mandatory = true
versionRange = "[40.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beekeeperhut]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beekeeperhut]]
modId = "friendsandfoes"
mandatory = true
versionRange = "[1.5.7,)"
ordering = "NONE"
side = "BOTH"
