modLoader = "javafml"
loaderVersion = "[43,)"
license = "CC BY-NC-ND 4.0"
issueTrackerURL = "https://github.com/Faboslav/friends-and-foes-beekeeper-hut-beekeeper-hut/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-beekeeper-hut-forge"

[[dependencies.${ modId }]]
modId = "forge"
mandatory = true
versionRange = "[43.1.1,)"

[[dependencies.${ modId }]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"

[[dependencies.${ modId }]]
modId = "friendsandfoes"
mandatory = true
versionRange = "[1.6.5,)"
ordering = "NONE"
side = "BOTH"
