modLoader = "javafml"
loaderVersion = "*"
license = "CC BY-NC-ND 4.0"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-beekeeper-hut-forge"
issueTrackerURL = "https://github.com/Faboslav/friends-and-foes-beekeeper-hut-beekeeper-hut/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"
logoBlur = false

[[dependencies.${ modId }]]
modId = "minecraft"
required = true
versionRange = "[${minecraftVersion},)"

[[dependencies.${ modId }]]
modId = "friendsandfoes"
required = true
versionRange = "[2.0.7,)"