modLoader = "javafml"
loaderVersion = "*"
license = "${modLicense}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-beekeeper-hut-forge"
issueTrackerURL = "https://github.com/Faboslav/friends-and-foes-beekeeper-hut-beekeeper-hut/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"
logoBlur = false

[[dependencies.${ modId }]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "minecraft"
type = "required"
versionRange = "[${minMinecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "friendsandfoes"
type = "required"
versionRange = "[${friendsAndFoesVersion},)"
ordering = "NONE"
side = "BOTH"
[dependencies.${ modId }.mc-publish]
ignore = false
modrinth = "friends-and-foes-forge"
curseforge = "friends-and-foes-forge"