name: "Build"

on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - "**"
            - "!master"

jobs:
    build:
        runs-on: ubuntu-latest

        name: "Build"
        timeout-minutes: 15

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v4.1.1
                with:
                    fetch-depth: 0

            -   name: "Set up JDK"
                uses: actions/setup-java@v4.0.0
                with:
                    java-version: 17
                    distribution: temurin

            -   name: "Setup Gradle"
                uses: gradle/gradle-build-action@v2.11.1
                with:
                    cache-read-only: false

            -   name: "Run Gradle build"
                run: ./gradlew build --no-daemon

    run-minecraft:
        needs: build
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                mod_loader: [fabric, forge]
                script: [client, server]

        name: Run ${{ matrix.mod_loader }} ${{ matrix.script }}
        timeout-minutes: 15

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3.5.3
                with:
                    fetch-depth: 0

            -   name: "Setup environment"
                uses: ./.github/actions/setup-environment

            -   name: Run ${{ matrix.mod_loader }} ${{ matrix.script }}
                uses: modmuss50/xvfb-action@v1
                with:
                    run: ./.github/scripts/run-${{ matrix.script }}.sh ${{ matrix.mod_loader }}
                    shell: bash